#!/usr/bin/env python
"""Build the visual showcase used by the project README and gallery.

The script reads the curated CSV result tables in ``results/tables`` and writes
publication-friendly PNG/SVG figures into ``results/figures/showcase``.  It
also copies selected trajectory and reward-mechanism media generated by the
experiment pipelines so the GitHub repository has both quantitative and
qualitative evidence.
"""

from __future__ import annotations

import json
import math
import shutil
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib import font_manager
from matplotlib.patches import FancyBboxPatch


ROOT = Path(__file__).resolve().parents[2]
TABLE_DIR = ROOT / "results" / "tables"
FIG_DIR = ROOT / "results" / "figures" / "showcase"

SOURCE_TRAJECTORY = (
    Path(r"F:\bishe\GeoExplorer\analysis")
    / "pipeline_20260517_anchor0624_visualization"
)
SOURCE_REWARD = (
    Path(r"F:\bishe\GeoExplorer\analysis")
    / "pipeline_20260518_reward_storytelling"
)

DIST_COLS = ["d4", "d5", "d6", "d7", "d8"]
DIST_LABELS = ["C=4", "C=5", "C=6", "C=7", "C=8"]

METHOD_LABEL = {
    "GeoExplorer-anchor0624": "Ours",
    "anchor0624": "Ours",
    "GOMAA-Geo": "GOMAA-Geo",
    "gomaa": "GOMAA-Geo",
    "GeoExplorer": "GeoExplorer",
    "GeoExplorer-pristine": "GeoExplorer",
    "pristine": "GeoExplorer",
    "Random policy": "Random",
    "DiT-AGL": "DiT-AGL",
    "AiRLoc": "AiRLoc",
    "本文方法": "Ours",
}

PALETTE = {
    "Ours": "#0077BB",
    "GOMAA-Geo": "#EE7733",
    "GeoExplorer": "#7A869A",
    "Random": "#B8BCC7",
    "DiT-AGL": "#CC3311",
    "AiRLoc": "#009988",
    "PBRS on": "#0077BB",
    "PBRS off": "#D55E00",
}


def read_csv(rel: str) -> pd.DataFrame:
    return pd.read_csv(TABLE_DIR / rel)


def normalize_method(value: str) -> str:
    if pd.isna(value):
        return ""
    text = str(value)
    return METHOD_LABEL.get(text, text)


def prepare_dirs() -> None:
    for path in [
        FIG_DIR,
        FIG_DIR / "trajectories" / "gifs",
        FIG_DIR / "trajectories" / "comparison_png",
        FIG_DIR / "trajectories" / "static_png",
        FIG_DIR / "reward_story" / "gifs",
        FIG_DIR / "dataset",
    ]:
        path.mkdir(parents=True, exist_ok=True)


def set_style() -> None:
    font_manager.fontManager.addfont("C:/Windows/Fonts/times.ttf")
    font_manager.fontManager.addfont("C:/Windows/Fonts/timesbd.ttf")
    font_manager.fontManager.addfont("C:/Windows/Fonts/simsun.ttc")
    plt.rcParams.update(
        {
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "font.family": ["Times New Roman", "SimSun"],
            "font.serif": ["Times New Roman", "SimSun"],
            "font.sans-serif": ["Times New Roman", "SimSun"],
            "axes.edgecolor": "#D7DCE3",
            "axes.labelcolor": "#1F2937",
            "xtick.color": "#374151",
            "ytick.color": "#374151",
            "axes.titleweight": "bold",
            "axes.titlesize": 13,
            "axes.labelsize": 11,
            "xtick.labelsize": 10,
            "ytick.labelsize": 10,
            "legend.fontsize": 10,
            "svg.fonttype": "none",
            "axes.unicode_minus": False,
        }
    )


def finish_ax(ax: plt.Axes, grid_axis: str = "y") -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color("#D7DCE3")
    ax.spines["bottom"].set_color("#D7DCE3")
    if grid_axis:
        ax.grid(axis=grid_axis, alpha=0.25, color="#9AA4B2", linewidth=0.8)
    ax.set_axisbelow(True)


def save_figure(fig: plt.Figure, stem: str) -> None:
    fig.tight_layout()
    png_path = FIG_DIR / f"{stem}.png"
    svg_path = FIG_DIR / f"{stem}.svg"
    fig.savefig(png_path, dpi=220, bbox_inches="tight")
    fig.savefig(svg_path, bbox_inches="tight")
    strip_trailing_whitespace(svg_path)
    plt.close(fig)


def strip_trailing_whitespace(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    cleaned = "\n".join(line.rstrip() for line in text.splitlines()) + "\n"
    path.write_text(cleaned, encoding="utf-8")


def label_bars(ax: plt.Axes, fmt: str = "{:.3f}", dx: float = 0.006) -> None:
    for patch in ax.patches:
        width = patch.get_width()
        if not np.isfinite(width):
            continue
        ax.text(
            width + dx,
            patch.get_y() + patch.get_height() / 2,
            fmt.format(width),
            va="center",
            ha="left",
            fontsize=9,
            color="#111827",
        )


def benchmark_overview_dashboard() -> None:
    df = read_csv("main_benchmark/paper_baseline_compare_table.csv")
    df["method_clean"] = df["method"].map(normalize_method)
    pair = df[df["method_clean"].isin(["Ours", "GOMAA-Geo"])].copy()
    pivot = pair.pivot_table(
        index="benchmark", columns="method_clean", values="success_ratio", aggfunc="first"
    ).dropna()
    pivot["gain"] = pivot["Ours"] - pivot["GOMAA-Geo"]
    pivot = pivot.sort_values("gain", ascending=True)

    ultra = read_csv("ultra_long/ultra_long_v2_summary.csv")
    ultra["method_clean"] = ultra["method_key"].map(normalize_method)
    ultra_ours = ultra[ultra["method_key"].eq("anchor0624")]["success_ratio"].mean()
    ultra_gomaa = ultra[ultra["method_key"].eq("gomaa")]["success_ratio"].mean()

    fig = plt.figure(figsize=(14, 8))
    gs = fig.add_gridspec(2, 4, height_ratios=[1.1, 3.0])
    cards = [
        ("Shared Mean SR", pivot["Ours"].mean(), "#0077BB"),
        ("GOMAA Mean SR", pivot["GOMAA-Geo"].mean(), "#EE7733"),
        ("Mean Gain", pivot["gain"].mean(), "#009988"),
        ("Long-range Gain", ultra_ours - ultra_gomaa, "#8F5D00"),
    ]
    for i, (title, value, color) in enumerate(cards):
        ax = fig.add_subplot(gs[0, i])
        ax.set_axis_off()
        card = FancyBboxPatch(
            (0.02, 0.05),
            0.96,
            0.85,
            boxstyle="round,pad=0.025,rounding_size=0.045",
            linewidth=1.2,
            edgecolor="#E5E7EB",
            facecolor="#F8FAFC",
        )
        ax.add_patch(card)
        ax.text(0.08, 0.70, title, fontsize=12, color="#4B5563", transform=ax.transAxes)
        sign = "+" if "Gain" in title and value >= 0 else ""
        ax.text(
            0.08,
            0.30,
            f"{sign}{value:.3f}",
            fontsize=28,
            fontweight="bold",
            color=color,
            transform=ax.transAxes,
        )

    ax = fig.add_subplot(gs[1, :])
    y = np.arange(len(pivot))
    ax.barh(y - 0.17, pivot["GOMAA-Geo"], height=0.34, color=PALETTE["GOMAA-Geo"], label="GOMAA-Geo")
    ax.barh(y + 0.17, pivot["Ours"], height=0.34, color=PALETTE["Ours"], label="Ours")
    ax.set_yticks(y)
    ax.set_yticklabels([x.replace("_", " ") for x in pivot.index])
    ax.set_xlim(0, max(0.75, pivot[["Ours", "GOMAA-Geo"]].max().max() + 0.08))
    ax.set_xlabel("Success rate")
    ax.set_title("Ours leads GOMAA-Geo across the shared benchmark suite")
    ax.legend(loc="lower right", frameon=False)
    for idx, (_, row) in enumerate(pivot.iterrows()):
        ax.text(
            row["Ours"] + 0.008,
            idx + 0.17,
            f"+{row['gain']:.3f}",
            va="center",
            fontsize=8.5,
            color="#0077BB",
            fontweight="bold",
        )
    finish_ax(ax)
    save_figure(fig, "benchmark_overview_dashboard")


def mmgag_modality_sr() -> None:
    df = read_csv("main_benchmark/paper_baseline_compare_table.csv")
    df["method_clean"] = df["method"].map(normalize_method)
    rows = df[df["benchmark"].isin(["mmgag_aerial", "mmgag_ground", "mmgag_text"])].copy()
    rows["target"] = rows["benchmark"].map(
        {"mmgag_aerial": "Aerial goal", "mmgag_ground": "Ground goal", "mmgag_text": "Text goal"}
    )

    airloc_path = TABLE_DIR / "main_benchmark" / "airloc_mmgag_aerial_table_row.csv"
    if airloc_path.exists():
        airloc = pd.read_csv(airloc_path).iloc[0]
        rows = pd.concat(
            [
                rows,
                pd.DataFrame(
                    [
                        {
                            "method_clean": "AiRLoc",
                            "target": "Aerial goal",
                            "success_ratio": float(airloc["sr"]),
                        }
                    ]
                ),
            ],
            ignore_index=True,
        )

    methods = ["Ours", "GOMAA-Geo", "AiRLoc", "Random", "DiT-AGL"]
    targets = ["Aerial goal", "Ground goal", "Text goal"]
    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    x = np.arange(len(targets))
    width = 0.15
    for i, method in enumerate(methods):
        values = []
        for target in targets:
            hit = rows[(rows["target"].eq(target)) & (rows["method_clean"].eq(method))]
            values.append(float(hit["success_ratio"].iloc[0]) if len(hit) else np.nan)
        offset = (i - (len(methods) - 1) / 2) * width
        bars = ax.bar(
            x + offset,
            values,
            width=width,
            label=method,
            color=PALETTE.get(method, "#94A3B8"),
            alpha=1.0 if method == "Ours" else 0.85,
        )
        for bar, value in zip(bars, values):
            if np.isfinite(value):
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    value + 0.012,
                    f"{value:.3f}",
                    ha="center",
                    va="bottom",
                    fontsize=8,
                    rotation=90 if method in ["Random", "DiT-AGL"] else 0,
                )
    ax.set_xticks(x)
    ax.set_xticklabels(targets)
    ax.set_ylim(0, 0.72)
    ax.set_ylabel("Success rate")
    ax.set_title("MM-GAG cross-modal evaluation: strongest gains on all target forms")
    ax.legend(ncol=5, frameon=False, loc="upper center", bbox_to_anchor=(0.5, -0.10))
    finish_ax(ax)
    save_figure(fig, "mmgag_modality_sr")


def distance_bucket_curves() -> None:
    df = read_csv("main_benchmark/paper_baseline_compare_table.csv")
    df["method_clean"] = df["method"].map(normalize_method)
    rows = df[df["benchmark"].eq("mmgag_aerial")].copy()

    airloc_path = TABLE_DIR / "main_benchmark" / "airloc_mmgag_aerial_table_row.csv"
    if airloc_path.exists():
        airloc = pd.read_csv(airloc_path).iloc[0]
        rows = pd.concat(
            [
                rows,
                pd.DataFrame(
                    [
                        {
                            "method_clean": "AiRLoc",
                            "d4": airloc["c4_sr"],
                            "d5": airloc["c5_sr"],
                            "d6": airloc["c6_sr"],
                            "d7": airloc["c7_sr"],
                            "d8": airloc["c8_sr"],
                        }
                    ]
                ),
            ],
            ignore_index=True,
        )

    fig, ax = plt.subplots(figsize=(9.5, 5.6))
    x = np.arange(4, 9)
    for method in ["Ours", "GOMAA-Geo", "AiRLoc", "Random", "DiT-AGL"]:
        hit = rows[rows["method_clean"].eq(method)]
        if hit.empty:
            continue
        values = hit.iloc[0][DIST_COLS].astype(float).values
        ax.plot(
            x,
            values,
            marker="o",
            linewidth=2.8 if method == "Ours" else 2.0,
            color=PALETTE.get(method, "#64748B"),
            label=method,
        )
        ax.text(x[-1] + 0.05, values[-1], method, color=PALETTE.get(method, "#64748B"), va="center")
    ax.set_xticks(x)
    ax.set_xticklabels(DIST_LABELS)
    ax.set_ylim(0, 1.02)
    ax.set_ylabel("Success rate")
    ax.set_title("MM-GAG aerial: advantage becomes clearer at medium and long distances")
    finish_ax(ax)
    save_figure(fig, "distance_bucket_curves")


def generalization_heatmap_16cell() -> None:
    df = read_csv("ablation/anchor0624_generalization_table.csv")
    df["gp"] = df.apply(lambda r: f"G{int(r['G_gate'])} P{int(r['P_pbrs'])}", axis=1)
    df["ev"] = df.apply(lambda r: f"E{int(r['E_low_entropy'])} V{int(r['V_val78'])}", axis=1)
    row_order = ["G0 P0", "G0 P1", "G1 P0", "G1 P1"]
    col_order = ["E0 V0", "E0 V1", "E1 V0", "E1 V1"]
    mat = df.pivot(index="gp", columns="ev", values="primary_generalization_mean").reindex(
        row_order
    )[col_order]

    fig, ax = plt.subplots(figsize=(8.5, 5.8))
    soft_cmap = LinearSegmentedColormap.from_list(
        "soft_teal_blue",
        ["#F1FAF8", "#D8F0EF", "#A9D7E4", "#72B3D0", "#3F83B7"],
    )
    im = ax.imshow(mat.values, cmap=soft_cmap, vmin=0.54, vmax=0.625)
    ax.set_xticks(np.arange(len(col_order)))
    ax.set_xticklabels(col_order)
    ax.set_yticks(np.arange(len(row_order)))
    ax.set_yticklabels(row_order)
    ax.set_title("Full G+P+E+V branch is the best 16-cell ablation result")
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            value = mat.iloc[i, j]
            ax.text(
                j,
                i,
                f"{value:.3f}",
                ha="center",
                va="center",
                color="#111827",
                fontsize=13,
                fontweight="bold" if value == np.nanmax(mat.values) else "semibold",
            )
    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("Primary generalization mean")
    save_figure(fig, "generalization_heatmap_16cell")


def ablation_factor_effects() -> None:
    df = read_csv("ablation/anchor0624_generalization_table.csv")
    factors = [
        ("G: distance gate", "G_gate"),
        ("P: PBRS", "P_pbrs"),
        ("E: lower entropy", "E_low_entropy"),
        ("V: val C=7,8", "V_val78"),
    ]
    data = []
    for label, col in factors:
        on = df[df[col].eq(1)]["primary_generalization_mean"].mean()
        off = df[df[col].eq(0)]["primary_generalization_mean"].mean()
        data.append((label, on, off, on - off))
    plot = pd.DataFrame(data, columns=["factor", "on", "off", "effect"])
    plot = plot.sort_values("effect")

    fig, ax = plt.subplots(figsize=(9, 5.2))
    colors = ["#0077BB" if v >= 0 else "#CC3311" for v in plot["effect"]]
    ax.barh(plot["factor"], plot["effect"], color=colors, height=0.58)
    ax.axvline(0, color="#111827", linewidth=1)
    for i, row in enumerate(plot.itertuples(index=False)):
        ha = "left" if row.effect >= 0 else "right"
        dx = 0.0025 if row.effect >= 0 else -0.0025
        ax.text(row.effect + dx, i, f"{row.effect:+.3f}", va="center", ha=ha, fontweight="bold")
    ax.set_xlabel("Mean effect on primary generalization SR")
    ax.set_title("Ablation main effects: validation focus and PBRS contribute most on average")
    finish_ax(ax)
    save_figure(fig, "ablation_factor_effects")


def reward_gate_pb_comparison() -> None:
    df = read_csv("ablation/reward_gate_type_mmgag_only_table_with_linear.csv")
    df = df.sort_values("mmgag_mean_sr", ascending=True)
    labels = (
        df["value"]
        .astype(str)
        .str.replace("_0.405", " 0.405", regex=False)
        .str.replace("_", " ", regex=False)
    )
    colors = [
        PALETTE["PBRS on"] if ("pb" in str(v) and "no pb" not in str(v).replace("_", " ")) else PALETTE["PBRS off"]
        for v in df["value"]
    ]

    fig, ax = plt.subplots(figsize=(9.5, 6.4))
    ax.barh(labels, df["mmgag_mean_sr"], color=colors, height=0.58)
    ax.set_xlim(0, max(0.65, df["mmgag_mean_sr"].max() + 0.04))
    label_bars(ax)
    ax.set_xlabel("MM-GAG mean SR")
    ax.set_title("Reward gate functions: linear distance gate + PBRS is the strongest row")
    handles = [
        plt.Line2D([0], [0], color=PALETTE["PBRS on"], lw=8, label="PBRS on"),
        plt.Line2D([0], [0], color=PALETTE["PBRS off"], lw=8, label="PBRS off / external only"),
    ]
    ax.legend(handles=handles, frameon=False, loc="lower right")
    finish_ax(ax)
    save_figure(fig, "reward_gate_pb_comparison")


def reward_control_endpoints() -> None:
    control = read_csv("ablation/reward_control_long_table.csv")
    mmgag = control[control["benchmark"].isin(["mmgag_aerial", "mmgag_ground", "mmgag_text"])]
    grouped = mmgag.groupby("run")["sr"].mean().reset_index()
    name_map = {
        "reward_external_only_seed321_t480k": "External only",
        "reward_intrinsic_only_seed321_t480k": "Intrinsic only",
        "reward_intrinsic_no_decay_seed321_t480k": "Ext+Int, no gate/PBRS",
    }
    grouped["label"] = grouped["run"].map(name_map).fillna(grouped["run"])

    gate = read_csv("ablation/reward_gate_type_mmgag_only_table_with_linear.csv")
    ours = float(gate[gate["value"].eq("linear_0.405_pb")]["mmgag_mean_sr"].iloc[0])
    rows = pd.concat(
        [
            grouped[["label", "sr"]].rename(columns={"sr": "mmgag_mean_sr"}),
            pd.DataFrame([{"label": "Full reward (ours)", "mmgag_mean_sr": ours}]),
        ],
        ignore_index=True,
    ).sort_values("mmgag_mean_sr", ascending=True)

    fig, ax = plt.subplots(figsize=(8.5, 4.9))
    colors = ["#B8BCC7"] * len(rows)
    colors[list(rows["label"]).index("Full reward (ours)")] = PALETTE["Ours"]
    ax.barh(rows["label"], rows["mmgag_mean_sr"], color=colors, height=0.58)
    ax.set_xlim(0, 0.66)
    label_bars(ax)
    ax.set_xlabel("MM-GAG mean SR")
    ax.set_title("Strict reward controls show intrinsic reward alone is not sufficient")
    finish_ax(ax)
    save_figure(fig, "reward_control_endpoints")


def parameter_sensitivity_curves() -> None:
    base = read_csv("appendix/appendix_param_sr_table.csv")
    dense = read_csv("appendix/appendix_gate_valdist_sr_table.csv")

    fig, axes = plt.subplots(2, 3, figsize=(14.5, 8.2))
    axes = axes.ravel()

    gate = dense[dense["family"].eq("gate_floor_dense")].copy()
    gate["x"] = gate["value"].astype(float)
    gate = gate.sort_values("x")
    axes[0].plot(gate["x"], gate["mean_all_sr"], marker="o", color=PALETTE["Ours"], label="All")
    axes[0].plot(gate["x"], gate["mean_transfer_sr"], marker="o", color="#009988", label="Transfer")
    axes[0].axvline(0.405, color="#111827", linestyle="--", linewidth=1, alpha=0.55)
    axes[0].set_title("Gate floor full-range sweep")
    axes[0].set_xlabel("Gate floor")
    axes[0].set_ylabel("SR")
    axes[0].legend(frameon=False)

    pbrs = base[base["family"].eq("pbrs_coef")].copy()
    pbrs["x"] = pbrs["value"].astype(float)
    pbrs = pbrs.sort_values("x")
    axes[1].plot(pbrs["x"], pbrs["mean_all_sr"], marker="o", color=PALETTE["Ours"])
    axes[1].set_title("PBRS coefficient")
    axes[1].set_xlabel("Coefficient")
    axes[1].set_ylabel("Mean all SR")

    ent = base[base["family"].eq("ent_coef")].copy()
    ent["x"] = ent["value"].astype(float)
    ent = ent.sort_values("x")
    axes[2].plot(ent["x"], ent["mean_all_sr"], marker="o", color="#8F5D00")
    axes[2].set_title("Entropy coefficient")
    axes[2].set_xlabel("Entropy coef")
    axes[2].set_ylabel("Mean all SR")

    budget = base[base["family"].eq("train_budget")].copy()
    budget["x"] = budget["value"].str.replace("k", "", regex=False).astype(float)
    budget = budget.sort_values("x")
    axes[3].plot(budget["x"], budget["mean_all_sr"], marker="o", color="#0077BB")
    axes[3].set_title("Training budget")
    axes[3].set_xlabel("Steps (k)")
    axes[3].set_ylabel("Mean all SR")

    val = pd.concat(
        [base[base["family"].eq("val_dists")], dense[dense["family"].eq("val_dists_bias")]],
        ignore_index=True,
    ).copy()
    val["n_bucket"] = val["value"].astype(str).map(lambda x: len(x.split(",")))
    val = val.sort_values(["n_bucket", "value"])
    y = np.arange(len(val))
    axes[4].barh(y, val["mean_all_sr"], color="#009988", height=0.58)
    axes[4].set_yticks(y)
    axes[4].set_yticklabels(val["value"])
    axes[4].set_title("Validation distance set")
    axes[4].set_xlabel("Mean all SR")

    axes[5].axis("off")
    text = (
        "Reading note\n"
        "- Curves are checkpoints trained under the same family design.\n"
        "- The best single value is not always the thesis default.\n"
        "- Use these plots as sensitivity evidence, not as a new main method."
    )
    axes[5].text(0.04, 0.82, text, fontsize=12, va="top", color="#1F2937")

    for ax in axes[:5]:
        finish_ax(ax)
    save_figure(fig, "parameter_sensitivity_curves")


def dataset_training_transfer() -> None:
    sr = read_csv("appendix/appendix_dataset_sr_table.csv").sort_values("mean_all_sr")
    fig, ax = plt.subplots(figsize=(9.8, 5.8))
    y = np.arange(len(sr))
    ax.barh(y - 0.18, sr["mean_all_sr"], height=0.34, color="#0077BB", label="All benchmarks")
    ax.barh(y + 0.18, sr["mean_transfer_sr"], height=0.34, color="#009988", label="Transfer benchmarks")
    ax.set_yticks(y)
    ax.set_yticklabels(sr["value"])
    ax.set_xlim(0, 0.66)
    ax.set_xlabel("Success rate")
    ax.set_title("Training data comparison: MASA+MM-GAG is the strongest overall choice")
    ax.legend(frameon=False, loc="lower right")
    finish_ax(ax)
    save_figure(fig, "dataset_training_transfer")


def seed_stability() -> None:
    df = read_csv("appendix/appendix_seed_stability_table.csv").sort_values("seed")
    fig, ax = plt.subplots(figsize=(7.8, 4.8))
    ax.plot(df["seed"].astype(str), df["mean_all_sr"], marker="o", linewidth=2.5, label="All")
    ax.plot(df["seed"].astype(str), df["mean_transfer_sr"], marker="o", linewidth=2.5, label="Transfer")
    for _, row in df.iterrows():
        ax.text(str(row["seed"]), row["mean_all_sr"] + 0.008, f"{row['mean_all_sr']:.3f}", ha="center")
    ax.set_ylim(0.42, 0.62)
    ax.set_xlabel("Seed")
    ax.set_ylabel("Success rate")
    ax.set_title("Seed stability repeats: useful variance estimate for appendix")
    ax.legend(frameon=False)
    finish_ax(ax)
    save_figure(fig, "seed_stability")


def ultra_long_curves() -> None:
    df = read_csv("ultra_long/ultra_long_v2_per_distance.csv")
    df["method_clean"] = df["method_key"].map(normalize_method)
    order = ["GOMAA-Geo", "GeoExplorer", "Ours"]

    for metric, ylabel, stem, title_suffix in [
        ("success_ratio", "Success rate", "ultra_long_sr_curves", "success rate"),
        ("sg_mean", "SG mean (lower is better)", "ultra_long_sg_curves", "step gap"),
    ]:
        fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.0), sharey=False)
        for ax, grid in zip(axes, ["8x8", "10x10"]):
            sub = df[df["grid"].eq(grid)]
            for method in order:
                hit = sub[sub["method_clean"].eq(method)].sort_values("distance")
                if hit.empty:
                    continue
                ax.plot(
                    hit["distance"],
                    hit[metric],
                    marker="o",
                    linewidth=2.7 if method == "Ours" else 2.0,
                    color=PALETTE.get(method, "#64748B"),
                    label=method,
                )
            ax.set_title(f"{grid}, budget={int(sub['budget'].iloc[0])}")
            ax.set_xlabel("Start-goal distance")
            ax.set_ylabel(ylabel)
            if metric == "success_ratio":
                ax.set_ylim(0, 1.0)
            finish_ax(ax)
        axes[0].legend(frameon=False, loc="lower right")
        fig.suptitle(f"Ultra-long grid stress test: {title_suffix}", fontsize=15, fontweight="bold")
        save_figure(fig, stem)


def grid25_stress_curves() -> None:
    df = read_csv("ultra_long/ultra_long_v3_grid25_per_distance.csv")
    df["method_clean"] = df["method_key"].map(normalize_method)
    fig, axes = plt.subplots(1, 2, figsize=(13.0, 5.0))
    for ax, metric, ylabel in [
        (axes[0], "success_ratio", "Success rate"),
        (axes[1], "sg_mean", "SG mean (lower is better)"),
    ]:
        for method in ["GOMAA-Geo", "GeoExplorer", "Ours"]:
            hit = df[df["method_clean"].eq(method)].sort_values("distance")
            ax.plot(
                hit["distance"],
                hit[metric],
                marker="o",
                linewidth=2.7 if method == "Ours" else 2.0,
                color=PALETTE.get(method, "#64748B"),
                label=method,
            )
        ax.set_xlabel("Start-goal distance")
        ax.set_ylabel(ylabel)
        ax.set_title(ylabel)
        finish_ax(ax)
    axes[0].legend(frameon=False)
    fig.suptitle("25x25 exploratory stress test: a harder regime with weaker absolute SR", fontsize=15, fontweight="bold")
    save_figure(fig, "grid25_stress_curves")


def trajectory_statistics() -> None:
    df = read_csv("main_benchmark/trajectory_records.csv")
    df["method_clean"] = df["method"].map(normalize_method)
    summary = (
        df.groupby(["method_clean", "distance"])
        .agg(success_rate=("success", "mean"), mean_detour=("detour_steps", "mean"), n=("success", "size"))
        .reset_index()
    )

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.2))
    for method in ["Ours", "GOMAA-Geo", "GeoExplorer"]:
        hit = summary[summary["method_clean"].eq(method)].sort_values("distance")
        if hit.empty:
            continue
        axes[0].plot(
            hit["distance"],
            hit["success_rate"],
            marker="o",
            linewidth=2.7 if method == "Ours" else 2.0,
            color=PALETTE.get(method, "#64748B"),
            label=method,
        )
        axes[1].plot(
            hit["distance"],
            hit["mean_detour"],
            marker="o",
            linewidth=2.7 if method == "Ours" else 2.0,
            color=PALETTE.get(method, "#64748B"),
            label=method,
        )
    axes[0].set_title("Qualitative case bank: success by distance")
    axes[0].set_xlabel("Distance")
    axes[0].set_ylabel("Success rate")
    axes[0].set_ylim(0, 1.02)
    axes[1].set_title("Qualitative case bank: detour steps")
    axes[1].set_xlabel("Distance")
    axes[1].set_ylabel("Mean detour steps")
    for ax in axes:
        finish_ax(ax)
    axes[0].legend(frameon=False, loc="lower right")
    save_figure(fig, "trajectory_statistics")

    pivot = summary.pivot(index="method_clean", columns="distance", values="success_rate").reindex(
        ["Ours", "GOMAA-Geo", "GeoExplorer"]
    )
    fig, ax = plt.subplots(figsize=(7.8, 3.8))
    im = ax.imshow(pivot.values, cmap="YlGnBu", vmin=0, vmax=1)
    ax.set_xticks(np.arange(pivot.shape[1]))
    ax.set_xticklabels([f"C={int(c)}" for c in pivot.columns])
    ax.set_yticks(np.arange(pivot.shape[0]))
    ax.set_yticklabels(pivot.index)
    for i in range(pivot.shape[0]):
        for j in range(pivot.shape[1]):
            value = pivot.iloc[i, j]
            ax.text(j, i, f"{value:.2f}", ha="center", va="center", color="white" if value > 0.55 else "#111827")
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="Success rate")
    ax.set_title("Trajectory visualization bank coverage")
    save_figure(fig, "trajectory_success_heatmap")

    fig, ax = plt.subplots(figsize=(9, 5))
    methods = ["Ours", "GOMAA-Geo", "GeoExplorer"]
    data = [df[df["method_clean"].eq(m)]["detour_steps"].clip(upper=12).values for m in methods]
    bp = ax.boxplot(data, tick_labels=methods, patch_artist=True, showfliers=False)
    for patch, method in zip(bp["boxes"], methods):
        patch.set_facecolor(PALETTE.get(method, "#CBD5E1"))
        patch.set_alpha(0.75)
    ax.set_ylabel("Detour steps, clipped at 12")
    ax.set_title("Path efficiency distribution over 2,205 recorded trajectories")
    finish_ax(ax)
    save_figure(fig, "trajectory_detour_distribution")


def main_benchmark_rankings() -> None:
    df = read_csv("main_benchmark/paper_baseline_compare_table.csv")
    df["method_clean"] = df["method"].map(normalize_method)
    subset = df[df["method_clean"].isin(["Ours", "GOMAA-Geo", "Random", "DiT-AGL"])]
    mean_by_method = subset.groupby("method_clean")["success_ratio"].mean().sort_values()

    fig, ax = plt.subplots(figsize=(8.5, 4.8))
    colors = [PALETTE.get(m, "#94A3B8") for m in mean_by_method.index]
    ax.hlines(mean_by_method.index, 0, mean_by_method.values, color=colors, linewidth=4, alpha=0.85)
    ax.scatter(mean_by_method.values, mean_by_method.index, color=colors, s=130, zorder=3)
    for method, value in mean_by_method.items():
        ax.text(value + 0.01, method, f"{value:.3f}", va="center", fontweight="bold")
    ax.set_xlim(0, max(0.65, mean_by_method.max() + 0.08))
    ax.set_xlabel("Mean SR over available paper-aligned rows")
    ax.set_title("Overall ranking across available benchmark rows")
    finish_ax(ax)
    save_figure(fig, "method_rank_lollipop")


def copy_media() -> dict[str, int]:
    counts: dict[str, int] = {}

    copy_specs = [
        (SOURCE_TRAJECTORY / "gif", FIG_DIR / "trajectories" / "gifs", ["*.gif"]),
        (SOURCE_TRAJECTORY / "comparison_png", FIG_DIR / "trajectories" / "comparison_png", ["*.png"]),
        (SOURCE_TRAJECTORY / "static_png", FIG_DIR / "trajectories" / "static_png", ["*.png"]),
        (SOURCE_REWARD / "figures", FIG_DIR / "reward_story", ["*.png", "*.svg"]),
        (SOURCE_REWARD / "gifs", FIG_DIR / "reward_story" / "gifs", ["*.gif"]),
    ]

    for src_dir, dst_dir, patterns in copy_specs:
        copied = 0
        if src_dir.exists():
            dst_dir.mkdir(parents=True, exist_ok=True)
            for pattern in patterns:
                for src in sorted(src_dir.glob(pattern)):
                    dst = dst_dir / src.name
                    shutil.copy2(src, dst)
                    if dst.suffix.lower() == ".svg":
                        strip_trailing_whitespace(dst)
                    copied += 1
        counts[str(dst_dir.relative_to(ROOT))] = copied

    dataset_specs = [
        ROOT / "results" / "figures" / "chapter2_dataset" / "figure_dataset_overview.png",
        ROOT / "results" / "figures" / "chapter2_dataset" / "chapter2_typical_dataset_scene_examples.png",
        ROOT / "results" / "figures" / "chapter3_method" / "figure3_1_method_overview_revised.png",
        ROOT / "results" / "figures" / "chapter4_trajectories" / "figure4_x_anchor_typical_c4_c6_c8.png",
        ROOT / "results" / "figures" / "chapter4_trajectories" / "figure4_y_three_method_hardcase_revised.png",
    ]
    copied = 0
    for src in dataset_specs:
        if src.exists():
            shutil.copy2(src, FIG_DIR / "dataset" / src.name)
            copied += 1
    counts[str((FIG_DIR / "dataset").relative_to(ROOT))] = copied
    return counts


def write_manifest(media_counts: dict[str, int]) -> None:
    files = sorted(
        str(p.relative_to(ROOT)).replace("\\", "/")
        for p in FIG_DIR.rglob("*")
        if p.is_file() and p.name not in {"showcase_manifest.json", "README.md"}
    )
    manifest = {
        "generated_by": "code/tools/build_visual_showcase.py",
        "figure_root": str(FIG_DIR.relative_to(ROOT)).replace("\\", "/"),
        "file_count": len(files),
        "media_counts": media_counts,
        "files": files,
    }
    (FIG_DIR / "showcase_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def build_all() -> None:
    prepare_dirs()
    set_style()
    benchmark_overview_dashboard()
    mmgag_modality_sr()
    distance_bucket_curves()
    generalization_heatmap_16cell()
    ablation_factor_effects()
    reward_gate_pb_comparison()
    reward_control_endpoints()
    parameter_sensitivity_curves()
    dataset_training_transfer()
    seed_stability()
    ultra_long_curves()
    grid25_stress_curves()
    trajectory_statistics()
    main_benchmark_rankings()
    media_counts = copy_media()
    try:
        from build_polished_showcase import build_polished

        build_polished()
    except Exception as exc:  # pragma: no cover - keep base showcase generation robust.
        print(f"Polished showcase generation skipped: {exc}")
    try:
        from build_showcase_experience import build_experience

        build_experience()
    except Exception as exc:  # pragma: no cover - keep base showcase generation robust.
        print(f"Experience showcase generation skipped: {exc}")
    write_manifest(media_counts)
    print(f"Showcase written to {FIG_DIR}")


if __name__ == "__main__":
    build_all()
